apiVersion: loadbalancer.harvesterhci.io/v1beta1
kind: IPPool
metadata:
  name: public-ip-pool
spec:
  selector:
    scope:
      - guestCluster: kubernetes
        project: c-t5jzt/p-dh8x5
        namespace: default
  ranges:
    - subnet: 51.38.122.160/29
      rangeStart: 51.38.122.164
      rangeEnd: 51.38.122.165
      gateway: 51.38.122.166
