apiVersion: loadbalancer.harvesterhci.io/v1beta1
kind: IPPool
metadata:
  name: public-ip-pool
spec:
  ranges:
    - subnet: 51.38.122.160/29
      rangeStart: 51.38.122.163
      rangeEnd: 51.38.122.165
      gateway: 51.38.122.166
  selector:
    network: default/vlan-mgmt
