apiVersion: loadbalancer.harvesterhci.io/v1beta1
kind: IPPool
metadata:
  name: public-ip-pool
  namespace: default
spec:
  ranges:
    - subnet: 51.38.122.160/29
      rangeStart: 51.38.122.164
      rangeEnd: 51.38.122.165
  selector:
    network: default/vlan-mgmt
