apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: harvesterpoc-platform
  namespace: fleet-default
spec:
  repo: https://github.com/SantoDE/harvesterpoc
  branch: main
  paths:
    - platform/traefik-config
    - platform/dapr
    - platform/redis
    - platform/knative-operator
    - platform/knative-serving
    - platform/knative-config
    - platform/submariner-broker
    - platform/submariner-operator
    - platform/traefik
    - platform/knative-serving-ovh
  targets:
    - clusterName: rke2-test
    - clusterName: c-rxv24
