apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  version: "1.16"
  ingress:
    istio:
      enabled: false
    kourier:
      enabled: false
  config:
    network:
      ingress-class: "gateway-api.ingress.networking.knative.dev"
    config-gateway:
      external-gateways: |
        - class: traefik
          gateway: kube-system/traefik-gateway
          service: kube-system/traefik
          supported-features:
          - HTTPRouteRequestTimeout
          - HTTPRouteBackendTimeout
          - HTTPRouteResponseHeaderModification
      local-gateways: |
        - class: traefik
          gateway: knative-serving/knative-local-gateway
          service: kube-system/traefik
    config-domain:
      51.38.122.164.sslip.io: ""
    config-observability:
      metrics.backend-destination: none
