apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: rancher
  namespace: default
  labels:
    harvesterhci.io/creator: harvester
    app: rancher
  annotations:
    harvesterhci.io/volumeClaimTemplates: '[{"metadata":{"name":"rancher-disk-0","annotations":{"harvesterhci.io/imageId":"default/image-2qvbl"}},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"20Gi"}},"volumeMode":"Block","storageClassName":"longhorn-image-2qvbl"}}]'
    network.harvesterhci.io/ips: '[]'
spec:
  running: true
  template:
    metadata:
      annotations:
        harvesterhci.io/sshNames: '["default/personal"]'
    spec:
      domain:
        cpu:
          cores: 2
          sockets: 1
          threads: 1
        memory:
          guest: 4Gi
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 2730Mi
        devices:
          disks:
          - disk:
              bus: virtio
            name: disk-0
          - disk:
              bus: virtio
            name: cloudinit
          interfaces:
          - name: nic-mgmt
            model: virtio
            bridge: {}
      evictionStrategy: LiveMigrateIfPossible
      hostname: rancher
      networks:
      - name: nic-mgmt
        multus:
          networkName: vlan-mgmt
      volumes:
      - dataVolume:
          name: rancher-disk-0
        name: disk-0
      - cloudInitNoCloud:
          secretRef:
            name: rancher-cloudinit
        name: cloudinit
