---
apiVersion: v1
kind: Secret
metadata:
  name: harvester-kubeconfig
  namespace: default
type: Opaque
stringData:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
    - name: "local"
      cluster:
        server: "https://51.38.122.161/k8s/clusters/local"
        certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2VENDQVdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKYkdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNVGMzTnprdwpNVFl5TnpBZUZ3MHlOakExTURReE1qTXpORGRhRncwek5qQTFNREV4TWpNek5EZGFNRVl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE56YzNPVEF4TmpJM01Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRWI1OVhyd1dGZkV6OAp4ZHdiNzVLaUxleFp4M1dSRTRLZGU0RE1mcURuTkJsckhFRW5EUHF4RC9nNC9iMVkzWjNZOG93TGtRa2NIN1BKClgwbm0rZ2Y5ZUtOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGQWY2NzFwc3BIWVBzWkh1bUJHbzNnL2RWUXE1TUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSUUvRApHM3puNzNiaEFIMVpUY0hqSXBBZVh4czlQVFMyUVNpdEczWmlzSkRYQWlFQThTL1lFaGJ2REQrZHk1c2FXemZCCng4OUNGMW43UCtRRnBDTnY4SVZRdGxFPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"
    users:
    - name: "local"
      user:
        token: "kubeconfig-user-xw788qsdf7:xbsnjmw9pmpb2nb5lpnzmz2lxg9cwp8pvkhv5gm5cn5gfqxjb6mr7z"
    contexts:
    - name: "local"
      context:
        user: "local"
        cluster: "local"
    current-context: "local"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: HarvesterCluster
metadata:
  name: workload
  namespace: default
spec:
  targetNamespace: default
  identitySecret:
    namespace: default
    name: harvester-kubeconfig
  loadBalancerConfig:
    ipamType: pool
    ipPool:
      vmNetwork: default/vlan-mgmt
      subnet: 51.38.122.160/29
      gateway: 51.38.122.166
      rangeStart: 51.38.122.164
      rangeEnd: 51.38.122.164
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: workload
  namespace: default
spec:
  controlPlaneEndpoint:
    host: 51.38.122.164
    port: 6443
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: HarvesterCluster
    name: workload
    namespace: default
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    kind: RKE2ControlPlane
    name: workload-cp
    namespace: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: HarvesterMachineTemplate
metadata:
  name: workload-cp-machine
  namespace: default
spec:
  template:
    spec:
      cpu: 2
      memory: 4Gi
      sshUser: ubuntu
      sshKeyPair: default/personal
      networks:
        - default/vlan-mgmt
      volumes:
        - volumeType: image
          imageName: default/image-2qvbl
          volumeSize: 20Gi
          bootOrder: 1
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: RKE2ControlPlane
metadata:
  name: workload-cp
  namespace: default
spec:
  replicas: 1
  version: v1.31.6+rke2r1
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
      kind: HarvesterMachineTemplate
      name: workload-cp-machine
      namespace: default
  rolloutStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  serverConfig:
    tlsSan:
      - 51.38.122.164
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: HarvesterMachineTemplate
metadata:
  name: workload-worker-machine
  namespace: default
spec:
  template:
    spec:
      cpu: 2
      memory: 4Gi
      sshUser: ubuntu
      sshKeyPair: default/personal
      networks:
        - default/vlan-mgmt
      volumes:
        - volumeType: image
          imageName: default/image-2qvbl
          volumeSize: 20Gi
          bootOrder: 1
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: RKE2ConfigTemplate
metadata:
  name: workload-worker-config
  namespace: default
spec:
  template:
    spec:
      agentConfig: {}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: workload-workers
  namespace: default
spec:
  clusterName: workload
  replicas: 1
  selector:
    matchLabels: {}
  template:
    spec:
      clusterName: workload
      version: v1.31.6+rke2r1
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
          kind: RKE2ConfigTemplate
          name: workload-worker-config
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: HarvesterMachineTemplate
        name: workload-worker-machine
