apiVersion: rke-machine-config.cattle.io/v1
kind: HarvesterConfig
metadata:
  name: workload-cp
  namespace: fleet-default
clusterName: workload
cpuCount: "2"
diskSize: "20"
imageName: default/image-2qvbl
memorySize: "4"
networkName: default/vlan-mgmt
networkData: |-
    version: 2
    ethernets:
      enp1s0:
        dhcp4: false
        addresses:
          - 192.168.1.3/24
        routes:
          - to: default
            via: 192.168.1.1
        nameservers:
          addresses:
            - 8.8.8.8
            - 1.1.1.1
sshUser: ubuntu
userData: |-
    #cloud-config
    users:
      - name: ubuntu
        sudo: ALL=(ALL) NOPASSWD:ALL
        shell: /bin/bash
        ssh_authorized_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDTQ5MYDuaMXG4FmXU28gVx8uQKBHn6oK1IBQxgUFTaGKGle0o7/B2ufC0kkGJKWW+/ETGtwZJMeyy2Mmmtxiyl/P7JHisROr7/6aQ9aHT7f4hTVMnJGOTucNAjhwHPDHclRzV+Gk0O+cGKTS54MRmIj+uGvm3s0K2WbAgOj1BUUg8CFzHAGftt9Zd77DO5wBthkp8rbwtc7aB11vq1Ei9NNflH/a8rjZL04YBtjZVhyRsVYiVlvh5QDzByp4gFuxovpxybpzGhf282j9dQR0BPFFRbPgrDaijbhkFHe9mcdv7XQknSA4okzmNmcsPpD9QvUlE8R6ff7sOghS2MjwSSaeZzTdGN3mua1r5ihaGLZoOzjni4jW/QL1AfHHENHitiC563unJA51fjHKP+HJTsj76c7FgdUxVMVK9CLMn5Rt1R8TM9dIbaksrZwGShsr0Z7dl2zib5Gw5W8/metb6BK4W6nUDauo1rx8eNSwc0ksKOletJiR3uHqWvoynmlXU=
    chpasswd:
      list: |
        ubuntu:harvester
      expire: false
    write_files:
      - encoding: b64
        content: YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIGNlcnRpZmljYXRlLWF1dGhvcml0eS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VKbGFrTkRRVklyWjBGM1NVSkJaMGxDUVVSQlMwSm5aM0ZvYTJwUFVGRlJSRUZxUVd0TlUwbDNTVUZaUkZaUlVVUkVRbXg1WVRKVmVVeFlUbXdLWTI1YWJHTnBNV3BaVlVGNFRucGpNMDlVUVhoT1ZGRTBUVUkwV0VSVVNUSk5SRlYzVGtSRmVrMTZTWGxQUm01WVJGUk5NazFFVlhkTlZFVjZUWHBKZVFwUFJtOTNTa1JGYVUxRFFVZEJNVlZGUVhkM1dtTnRkR3hOYVRGNldsaEtNbHBZU1hSWk1rWkJUVlJqTTA1NmEzZE5WRlV3VDBSQ1drMUNUVWRDZVhGSENsTk5ORGxCWjBWSFEwTnhSMU5OTkRsQmQwVklRVEJKUVVKUE5UUk5jazh6ZWpoSWQzbERaMU5CVFdWbGFGRnRSMkowYUdRM2VFMXhhMGMzVEZKbmRFVUtRMmRvVHpCSGJreE5lQzlMU0RrMldEWkhNbGxYTWxkaVkyVktVazVCUjNCQ2NsVjNRMk5RYVRkWlptSnJNRzFxVVdwQ1FVMUJORWRCTVZWa1JIZEZRZ292ZDFGRlFYZEpRM0JFUVZCQ1owNVdTRkpOUWtGbU9FVkNWRUZFUVZGSUwwMUNNRWRCTVZWa1JHZFJWMEpDVkRWTE0xUnViUzk0TlVGbU16QkNkbEI1Q2tKTGJra3pOSGR6WkhwQlMwSm5aM0ZvYTJwUFVGRlJSRUZuVGtwQlJFSkhRV2xGUVRsamNsQkRSalo0TWtNNFdIQldTeXRVY3pSNGNEQkVkRzB6WVU0S1lUWmtaSGxDUW0xamVEQmtTSFJ2UTBsUlEwd3llRW95UmxSV2JHbERVVWRVYUhaTGNWSkthWEJJY1dweWN6QjVlUzlOWXpONllUbEhiazQ0YzBFOVBRb3RMUzB0TFVWT1JDQkRSVkpVU1VaSlEwRlVSUzB0TFMwdENnPT0KICAgIHNlcnZlcjogaHR0cHM6Ly81MS4zOC4xMjIuMTYxOjY0NDMKICBuYW1lOiBkZWZhdWx0CmNvbnRleHRzOgotIGNvbnRleHQ6CiAgICBjbHVzdGVyOiBkZWZhdWx0CiAgICBuYW1lc3BhY2U6IGRlZmF1bHQKICAgIHVzZXI6IHdvcmtsb2FkLWRlZmF1bHQtZGVmYXVsdAogIG5hbWU6IHdvcmtsb2FkLWRlZmF1bHQtZGVmYXVsdApjdXJyZW50LWNvbnRleHQ6IHdvcmtsb2FkLWRlZmF1bHQtZGVmYXVsdApraW5kOiBDb25maWcKdXNlcnM6Ci0gbmFtZTogd29ya2xvYWQtZGVmYXVsdC1kZWZhdWx0CiAgdXNlcjoKICAgIHRva2VuOiBleUpoYkdjaU9pSlNVekkxTmlJc0ltdHBaQ0k2SW5kUFZ5MXpVamRmYkVkbE5FbHVZMVppYkRCa2R6WjJkREZNYTJ0cGFucFFiR1ZUTmtGS1kyWkVjbThpZlEuZXlKcGMzTWlPaUpyZFdKbGNtNWxkR1Z6TDNObGNuWnBZMlZoWTJOdmRXNTBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5dVlXMWxjM0JoWTJVaU9pSmtaV1poZFd4MElpd2lhM1ZpWlhKdVpYUmxjeTVwYnk5elpYSjJhV05sWVdOamIzVnVkQzl6WldOeVpYUXVibUZ0WlNJNkluZHZjbXRzYjJGa0xYUnZhMlZ1SWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXpaWEoyYVdObExXRmpZMjkxYm5RdWJtRnRaU0k2SW5kdmNtdHNiMkZrSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXpaWEoyYVdObExXRmpZMjkxYm5RdWRXbGtJam9pWVRrNVlUQXdORFV0TmpBek55MGtZemhoTFRrMk4ySXROekF6WmpZNE5tUXdOMkl5SWl3aWMzVmlJam9pYzNsemRHVnRPbk5sY25acFkyVmhZMk52ZFc1ME9tUmxabUYxYkhRNmQyOXlhMnh2WVdRaWZRLkpCc0ZYa0tmeklQMTVqWHBXMmo1NmFJbEpLOFpsbTQ2cVI5Sk1WeDZlOG5tQmM1VWgtbWQzTHNYeWNZeExWc0NSWURGMzdfall2dFFXX3VxVUk1YXJCZkN1Y3d0UGpoZ1IycVlZcjJyLVFXSVVFRnF2ekx5eklxd2hkWUt4QjVvTGVfaW1KUXQtT0ZDRktobFlUYU1LZXNvSDZ1TjB2MVpFajdOR3pZdndsZTRUX052RFNTWTI2aWl5U1dZTGRCZ09pYUxrWTh1MnZ4OHdpay0wZm5rbndKLTRnWHBhLWlSS3AzdU9PY2paMm51RVdFYkhianVKdXQySWRTOU50NE1MWlJJSmNQdGhYYm1RZzFVazRPTmhTN1IyaGVOUmFLU042cjdPUzV0REFfWGhkSUh4cEpKWGF4WmxmdTN0TzZqMl9UZXFFSXEwajRwVDR4OVZUR0FUUQo=
        owner: root:root
        path: /etc/kubernetes/cloud-config
        permissions: '0644'
    runcmd:
      - until ping -c1 8.8.8.8 &>/dev/null; do sleep 2; done
      - apt-get update -y
      - apt-get install -y qemu-guest-agent
      - systemctl start qemu-guest-agent
---
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: workload
  namespace: fleet-default
spec:
  kubernetesVersion: v1.32.4+k3s1
  rkeConfig:
    machineGlobalConfig:
      tls-san:
        - 51.38.122.164
        - 192.168.1.3
      disable-cloud-controller: true
      disable:
        - servicelb
    machineSelectorConfig:
      - config:
          kubelet-arg:
            - cloud-provider=external
          protect-kernel-defaults: false
    machinePools:
      - name: cp-pool
        controlPlaneRole: true
        etcdRole: true
        workerRole: true
        quantity: 1
        cloudCredentialSecretName: cattle-global-data:cc-8ljnf
        machineConfigRef:
          apiVersion: rke-machine-config.cattle.io/v1
          kind: HarvesterConfig
          name: workload-cp
    additionalManifest: |-
      apiVersion: helm.cattle.io/v1
      kind: HelmChart
      metadata:
        name: harvester-cloud-provider
        namespace: kube-system
      spec:
        targetNamespace: kube-system
        bootstrap: true
        repo: https://charts.harvesterhci.io/
        chart: harvester-cloud-provider
        version: 0.2.2
        helmVersion: v3
