apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-traefik
  namespace: kube-system
spec:
  valuesContent: |-
    experimental:
      knative: true
    additionalArguments:
      - "--providers.knative"
    providers:
      kubernetesGateway:
        enabled: true
    gatewayClass:
      enabled: true
      name: traefik
    gateway:
      listeners:
        web:
          namespacePolicy:
            from: All
    service:
      type: LoadBalancer
      annotations:
        cloudprovider.harvesterhci.io/ipam: pool
    rbac:
      enabled: true
      namespaced: false
    crds:
      enabled: false
    ports:
      websecure:
        expose:
          default: false
