apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-traefik
  namespace: kube-system
spec:
  valuesContent: |-
    providers:
      kubernetesGateway:
        enabled: true
    gatewayClass:
      enabled: true
      name: traefik
    service:
      annotations:
        cloudprovider.harvesterhci.io/ipam: pool
    rbac:
      enabled: true
      namespaced: false
