apiVersion: rke-machine-config.cattle.io/v1
kind: HarvesterConfig
metadata:
  name: rke2-test-cp
  namespace: fleet-default
clusterName: rke2-test
cpuCount: "4"
diskSize: "20"
imageName: default/image-2qvbl
memorySize: "8"
networkName: default/vlan-mgmt
networkData: |-
    version: 2
    ethernets:
      enp1s0:
        dhcp4: false
        addresses:
          - 192.168.1.20/24
        routes:
          - to: default
            via: 192.168.1.1
        nameservers:
          addresses:
            - 8.8.8.8
            - 1.1.1.1
sshUser: ubuntu
userData: |-
    #cloud-config
    users:
      - name: ubuntu
        sudo: ALL=(ALL) NOPASSWD:ALL
        shell: /bin/bash
        ssh_authorized_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDTQ5MYDuaMXG4FmXU28gVx8uQKBHn6oK1IBQxgUFTaGKGle0o7/B2ufC0kkGJKWW+/ETGtwZJMeyy2Mmmtxiyl/P7JHisROr7/6aQ9aHT7f4hTVMnJGOTucNAjhwHPDHclRzV+Gk0O+cGKTS54MRmIj+uGvm3s0K2WbAgOj1BUUg8CFzHAGftt9Zd77DO5wBthkp8rbwtc7aB11vq1Ei9NNflH/a8rjZL04YBtjZVhyRsVYiVlvh5QDzByp4gFuxovpxybpzGhf282j9dQR0BPFFRbPgrDaijbhkFHe9mcdv7XQknSA4okzmNmcsPpD9QvUlE8R6ff7sOghS2MjwSSaeZzTdGN3mua1r5ihaGLZoOzjni4jW/QL1AfHHENHitiC563unJA51fjHKP+HJTsj76c7FgdUxVMVK9CLMn5Rt1R8TM9dIbaksrZwGShsr0Z7dl2zib5Gw5W8/metb6BK4W6nUDauo1rx8eNSwc0ksKOletJiR3uHqWvoynmlXU=
    chpasswd:
      list: |
        ubuntu:harvester
      expire: false
    write_files:
      - encoding: b64
        content: YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIGluc2VjdXJlLXNraXAtdGxzLXZlcmlmeTogdHJ1ZQogICAgc2VydmVyOiBodHRwczovLzUxLjM4LjEyMi4xNjE6NjQ0MwogIG5hbWU6IGRlZmF1bHQKY29udGV4dHM6Ci0gY29udGV4dDoKICAgIGNsdXN0ZXI6IGRlZmF1bHQKICAgIG5hbWVzcGFjZTogZGVmYXVsdAogICAgdXNlcjogcmtlMi10ZXN0LWRlZmF1bHQtZGVmYXVsdAogIG5hbWU6IHJrZTItdGVzdC1kZWZhdWx0LWRlZmF1bHQKY3VycmVudC1jb250ZXh0OiBya2UyLXRlc3QtZGVmYXVsdC1kZWZhdWx0CmtpbmQ6IENvbmZpZwp1c2VyczoKLSBuYW1lOiBya2UyLXRlc3QtZGVmYXVsdC1kZWZhdWx0CiAgdXNlcjoKICAgIHRva2VuOiBleUpoYkdjaU9pSlNVekkxTmlJc0ltdHBaQ0k2SW5kUFZ5MXpVamRmYkVkbE5FbHVZMVppYkRCa2R6WjJkREZNYTJ0cGFucFFiR1ZUTmtGS1kydEVjbThpZlEuZXlKcGMzTWlPaUpyZFdKbGNtNWxkR1Z6TDNObGNuWnBZMlZoWTJOdmRXNTBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5dVlXMWxjM0JoWTJVaU9pSmtaV1poZFd4MElpd2lhM1ZpWlhKdVpYUmxjeTVwYnk5elpYSjJhV05sWVdOamIzVnVkQzl6WldOeVpYUXVibUZ0WlNJNkluSnJaVEl0ZEdWemRDMTBiMnRsYmlJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZ5ZG1salpTMWhZMk52ZFc1MExtNWhiV1VpT2lKeWEyVXlMWFJsYzNRaUxDSnJkV0psY201bGRHVnpMbWx2TDNObGNuWnBZMlZoWTJOdmRXNTBMM05sY25acFkyVXRZV05qYjNWdWRDNTFhV1FpT2lJeU1ETXhOVFJqTmkweFl6TXlMVFJrTmpRdE9EY3hNUzFpT1RreVpUazBZVGRtTURraUxDSnpkV0lpT2lKemVYTjBaVzA2YzJWeWRtbGpaV0ZqWTI5MWJuUTZaR1ZtWVhWc2REcHlhMlV5TFhSbGMzUWlmUS5VakhXM0k0U3d0RVgtUGVoT0taa0hkYmpjU0Z0d2NLUzlxNkhqaHAzSll5WUV3RlJLTmczaTRHQ3hlWThCQ21BVW80RFJwdjVWamszVkFvQzl2UW5RZ19MSG05NHV5Wl9pYlNqVWtTQnB4ZEpBTWFIR0owd3I5Wk11Y1I4MWsteW9DZV8xNnVyWWxudG5kVUYyb1lMUDl2WDg1Smdid0pLZ0JuMnRlWnAwMFV0b3RpVVJIT0tUNldGM1hoU0l4eDN5XzlJUlROOVg1UElFeFFZQlhZQU5ZQmttNHVTMjl6R0JQLUxIYXZ6SXl6emlhM21XTE9hOHoybE5pRE5jU0NkMDRJUWYyU0JfcFE5T2gtYUlyVG5lWjVZRHNtUjNKTU9ZSDg4Ym1xZmthYlZVVmJsekJ4Y0F1d052SzVGc2FjcndmMTNZM0M3Slp5Nl9EOHdiLU50d1EK
        owner: root:root
        path: /etc/kubernetes/cloud-config
        permissions: '0644'
    runcmd:
      - until ping -c1 8.8.8.8 &>/dev/null; do sleep 2; done
      - apt-get update -y
      - apt-get install -y qemu-guest-agent
      - systemctl start qemu-guest-agent
---
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: rke2-test
  namespace: fleet-default
spec:
  kubernetesVersion: v1.33.0+rke2r1
  cloudCredentialSecretName: cattle-global-data:cc-8ljnf
  rkeConfig:
    machineGlobalConfig:
      tls-san:
        - 192.168.1.20
      cloud-provider-name: harvester
      ingress-controller:
        - traefik
    machineSelectorConfig:
      - config:
          protect-kernel-defaults: false
    machinePools:
      - name: cp-pool
        controlPlaneRole: true
        etcdRole: true
        workerRole: true
        quantity: 1
        cloudCredentialSecretName: cattle-global-data:cc-8ljnf
        machineConfigRef:
          apiVersion: rke-machine-config.cattle.io/v1
          kind: HarvesterConfig
          name: rke2-test-cp
