apiVersion: rke-machine-config.cattle.io/v1
kind: HarvesterConfig
metadata:
  name: rke2-test-cp
  namespace: fleet-default
clusterName: rke2-test
cpuCount: "4"
diskSize: "20"
imageName: default/image-2qvbl
memorySize: "8"
networkName: default/vlan-mgmt
networkData: |-
    version: 2
    ethernets:
      enp1s0:
        dhcp4: false
        addresses:
          - 192.168.1.20/24
        routes:
          - to: default
            via: 192.168.1.1
        nameservers:
          addresses:
            - 8.8.8.8
            - 1.1.1.1
sshUser: ubuntu
userData: |-
    #cloud-config
    users:
      - name: ubuntu
        sudo: ALL=(ALL) NOPASSWD:ALL
        shell: /bin/bash
        ssh_authorized_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDTQ5MYDuaMXG4FmXU28gVx8uQKBHn6oK1IBQxgUFTaGKGle0o7/B2ufC0kkGJKWW+/ETGtwZJMeyy2Mmmtxiyl/P7JHisROr7/6aQ9aHT7f4hTVMnJGOTucNAjhwHPDHclRzV+Gk0O+cGKTS54MRmIj+uGvm3s0K2WbAgOj1BUUg8CFzHAGftt9Zd77DO5wBthkp8rbwtc7aB11vq1Ei9NNflH/a8rjZL04YBtjZVhyRsVYiVlvh5QDzByp4gFuxovpxybpzGhf282j9dQR0BPFFRbPgrDaijbhkFHe9mcdv7XQknSA4okzmNmcsPpD9QvUlE8R6ff7sOghS2MjwSSaeZzTdGN3mua1r5ihaGLZoOzjni4jW/QL1AfHHENHitiC563unJA51fjHKP+HJTsj76c7FgdUxVMVK9CLMn5Rt1R8TM9dIbaksrZwGShsr0Z7dl2zib5Gw5W8/metb6BK4W6nUDauo1rx8eNSwc0ksKOletJiR3uHqWvoynmlXU=
    chpasswd:
      list: |
        ubuntu:harvester
      expire: false
    write_files:
      - encoding: b64
        content: YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIGNlcnRpZmljYXRlLWF1dGhvcml0eS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VKbGFrTkRRVklyWjBGM1NVSkJaMGxDUVVSQlMwSm5aM0ZvYTJwUFVGRlJSRUZxUVd0TlUwbDNTVUZaUkZaUlVVUkVRbXg1WVRKVmVVeFlUbXdLWTI1YWJHTnBNV3BaVlVGNFRucGpNMDlVUVhoT1ZGRTBUVUkwV0VSVVNUWk5SRlYzVGtSRmVrMTZTWGxQUm05WVJGUk5NazFFVlhkTlZFVjZUWHBKZVFwUFJtOTNTa1JGYVUxRFFVZEJNVlZGUVhkM1dtTnRkR3hOYVRGNldsaEtNbHBZU1hSWk1rWkJUVlJqTTA1NmEzZE5WRlV3VDBSQ1drMUNUVWRDZVhGSENsTk5ORGxCWjBWSFEwTnhSMU5OTkRsQmQwVklRVEJKUVVKUE5UUk5jazh6ZWpoSWQzbERaMU5CVFdWbGFGRnRSMkowYUdRM2VFMXhhMGMzVEZKbmRFVUtRMmRvVHpCSGJreE5lQzlMU0RrMldEWkhNbGxYTWxkaVkyVktVazVCUjNCQ2NsVjNRMk5RYVRkWlptSnJNRzFxVVdwQ1FVMUJORWRCTVZWa1JIZEZRZ292ZDFGRlFYZEpRM0JFUVZCQ1owNVdTRkpOUWtGbU9FVkNWRUZFUVZGSUwwMUNNRWRCTVZWa1JHZFJWMEpDVkRWTE0xUnViUzk0TlVGbU16QkNkbEI1Q2tKTGJra3pOSGR6WkhwQlMwSm5aM0ZvYTJwUFVGRlJSRUZuVGtwQlJFSkhRV2xGUVRsamNsQkRSalo0TWtNNFdIQldTeXRVY3pSNGNEQkVkRzB6WVU0S1lUWmtaSGxDUW0xamVEQmtTSFJ2UTBsUlEwd3llRW95UmxSV2JHbERVVWRVYUhaTGNWSkthWEJJY1dweWN6QjVlUzlOWXpONllUbEhiazQ0YzBFOVBRb3RMUzB0TFVWT1JDQkRSVkpVU1VaSlEwRlVSUzB0TFMwdENnPT0KICAgIHNlcnZlcjogaHR0cHM6Ly81MS4zOC4xMjIuMTYxOjY0NDMKICBuYW1lOiBkZWZhdWx0CmNvbnRleHRzOgotIGNvbnRleHQ6CiAgICBjbHVzdGVyOiBkZWZhdWx0CiAgICBuYW1lc3BhY2U6IGRlZmF1bHQKICAgIHVzZXI6IHJrZTItdGVzdC1kZWZhdWx0LWRlZmF1bHQKICBuYW1lOiBya2UyLXRlc3QtZGVmYXVsdC1kZWZhdWx0CmN1cnJlbnQtY29udGV4dDogcmtlMi10ZXN0LWRlZmF1bHQtZGVmYXVsdApraW5kOiBDb25maWcKdXNlcnM6Ci0gbmFtZTogcmtlMi10ZXN0LWRlZmF1bHQtZGVmYXVsdAogIHVzZXI6CiAgICB0b2tlbjogZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNkluZFBWeTF6VWpkZmJFZGxORWx1WTFaaWJEQmtleloyZERGTWEydHBhbnBRYkdWVE5rRktZMnRFY204aWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUprWldaaGRXeDBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpXTnlaWFF1Ym1GdFpTSTZJbkpyWlRJdGRHVnpkQzEwYjJ0bGJpSXNJbXQxWW1WeWJtVjBaWE11YVc4dmMyVnlkbWxqWldGalkyOTFiblF2YzJWeWRtbGpaUzFoWTJOdmRXNTBMbTVoYldVaU9pSnlhMlV5TFhSbGMzUWlMQ0pyZFdKbGNtNWxkR1Z6TG1sdkwzTmxjblpwWTJWaFkyTnZkVzUwTDNObGNuWnBZMlV0WVdOamIzVnVkQzUxYVdRaU9pSXlNRE14TlRSak5pMHhZek15TFRSa05qUXRPRGN4TVMxaU9Ua3laVGswWVRkbU1Ea2lMQ0p6ZFdJaU9pSnplWE4wWlcwNmMyVnlkbWxqWldGalkyOTFiblE2WkdWbVlYVnNkRHB5YTJVeUxYUmxjM1FpZlEuVWpIVzNJNFN3dEVYLVBlaE9LWmtIZGJqY1NGdHdjS1M5cTZIamhwM0pZeVlFd0ZSS05nM2k0R0N4ZVk4QkNtQVVvNERScHY1VmprM1ZBb0M5dlFuUWdfTEhtOTR1eVpfaWJTalVrU0JweGRKQU1hSEdKMHdyOVpNdWNSODFrLXlvQ2VfMTZ1cllsbnRuZFVGMm9ZTFA5dlg4NUpnYndKS2dCbjJ0ZVpwMDBVdG90aVVSSE9LVDZXRjNYaFNJeHgzeV85SVJUTjlYNVBJRXhRWUJYWUFOWUJrbTR1UzI5ekdCUC1MSGF2ekl5enppYTNtV0xPYTh6MmxOaUROY1NDZDA0SVFmMlNCX3BROU9oLWFJclRuZVo1WURzbVIzSk1PWUg4OGJtcWZrYWJWVVZibHpCeGNBdXdOdks1RnNhY3J3ZjEzWTNDN0paeTZfRDh3Yi1OdHdRCg==
        owner: root:root
        path: /etc/kubernetes/cloud-config
        permissions: '0644'
    runcmd:
      - until ping -c1 8.8.8.8 &>/dev/null; do sleep 2; done
      - apt-get update -y
      - apt-get install -y qemu-guest-agent
      - systemctl start qemu-guest-agent
---
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: rke2-test
  namespace: fleet-default
spec:
  kubernetesVersion: v1.32.4+rke2r1
  cloudCredentialSecretName: cattle-global-data:cc-8ljnf
  rkeConfig:
    machineGlobalConfig:
      tls-san:
        - 192.168.1.20
      cloud-provider-name: harvester
    machineSelectorConfig:
      - config:
          protect-kernel-defaults: false
    machinePools:
      - name: cp-pool
        controlPlaneRole: true
        etcdRole: true
        workerRole: true
        quantity: 1
        cloudCredentialSecretName: cattle-global-data:cc-8ljnf
        machineConfigRef:
          apiVersion: rke-machine-config.cattle.io/v1
          kind: HarvesterConfig
          name: rke2-test-cp
