apiVersion: k3k.io/v1beta1
kind: Cluster
metadata:
  name: rancher
  namespace: k3k-rancher
spec:
  mode: virtual
  servers: 1
  expose:
    nodePort:
      serverPort: 30443
  tlsSANs:
    - 51.38.122.162
    - 51.195.5.176
  addons:
    - secretRef: cert-manager-addon
      secretNamespace: k3k-rancher
    - secretRef: traefik-addon
      secretNamespace: k3k-rancher
    - secretRef: rancher-addon
      secretNamespace: k3k-rancher
