apiVersion: v1
kind: Service
metadata:
  name: rancher-traefik
  namespace: k3k-rancher
spec:
  ports:
  - port: 443
    targetPort: 30444
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: rancher-traefik
  namespace: k3k-rancher
subsets:
- addresses:
  - ip: 51.38.122.162
  ports:
  - port: 30444
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rancher-proxy
  namespace: k3k-rancher
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  rules:
  - host: rancher.51.38.122.162.sslip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rancher-traefik
            port:
              number: 443
