apiVersion: v1
kind: Secret
metadata:
  name: rancher-addon
  namespace: k3k-rancher
type: Opaque
stringData:
  rancher.yaml: |
    apiVersion: helm.cattle.io/v1
    kind: HelmChart
    metadata:
      name: rancher
      namespace: kube-system
    spec:
      repo: https://releases.rancher.com/server-charts/latest
      chart: rancher
      targetNamespace: cattle-system
      createNamespace: true
      valuesContent: |-
        hostname: rancher.51.38.122.161.sslip.io
        bootstrapPassword: admin
        replicas: 1
